basePath: /api/v1
definitions:
  modules.Course:
    properties:
      CourseCategory:
        type: string
      CourseCode:
        type: string
      CourseName:
        type: string
      CourseStatus:
        type: string
      DateCreated:
        type: string
      PassMark:
        type: string
      QuestionCount:
        type: string
    type: object
  modules.Message:
    properties:
      message:
        example: message
        type: string
    type: object
  modules.Question:
    properties:
      CorrectOption:
        type: string
      CourseCode:
        type: string
      CourseName:
        type: string
      OptionA:
        type: string
      OptionB:
        type: string
      OptionC:
        type: string
      OptionD:
        type: string
      Question:
        type: string
      Reason:
        type: string
    type: object
  modules.Questions:
    properties:
      CorrectOption:
        type: string
      CourseCode:
        type: string
      CourseName:
        type: string
      DateCreated:
        type: string
      ID:
        type: integer
      IsAvailable:
        type: boolean
      OptionA:
        description: CourseCategory string `json:"CourseCategory" validate:"omitempty"`
        type: string
      OptionB:
        type: string
      OptionC:
        type: string
      OptionD:
        type: string
      Question:
        type: string
      Reason:
        type: string
      RecCount:
        type: integer
      Status:
        description: Active , non-Active
        type: string
    type: object
  modules.RequestResponse:
    properties:
      ResponseCode:
        type: string
      ResponseMessage:
        type: string
    type: object
  modules.ResponseManager:
    properties:
      ResponseCode:
        type: string
      ResponseDescription:
        type: string
    type: object
  modules.Student:
    properties:
      Category:
        type: string
      Email:
        type: string
      FirstName:
        type: string
      Gender:
        type: string
      LastName:
        type: string
      MiddleName:
        type: string
      Nationality:
        type: string
      UserType:
        type: string
    type: object
  modules.Students:
    properties:
      Category:
        type: string
      DateCreated:
        type: string
      Email:
        type: string
      FirstName:
        type: string
      Gender:
        type: string
      ID:
        type: integer
      LastName:
        type: string
      MiddleName:
        type: string
      Nationality:
        type: string
      Status:
        type: string
      UserType:
        type: string
    type: object
  modules.TblCourse:
    properties:
      CourseCategory:
        type: string
      CourseCode:
        type: string
      CourseName:
        type: string
      CourseStatus:
        type: string
      DateCreated:
        type: string
      ID:
        type: integer
      PassMark:
        type: string
      QuestionCount:
        type: string
    type: object
  modules.TestResult:
    properties:
      StudentID:
        type: string
      TestID:
        type: string
      TestResult:
        type: string
    type: object
  question.QuisRequest:
    properties:
      courseDetails:
        $ref: '#/definitions/modules.TblCourse'
        type: object
      myQuestion:
        items:
          $ref: '#/definitions/modules.Questions'
        type: array
      studentDetails:
        $ref: '#/definitions/modules.Students'
        type: object
    type: object
  question.RequestResponse:
    properties:
      ResponseCode:
        type: string
      ResponseMessage:
        type: string
    type: object
info:
  contact:
    email: alao.adebusy@gmail.com
    name: Alao ramon Adebisi
  description: Data science competency check API.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Data Science Central API
  version: "1.0"
paths:
  /course/CreateCourse:
    post:
      parameters:
      - description: Create new course
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modules.Course'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules.Message'
      summary: create new course
  /question/CreateNewQuestion/:
    post:
      parameters:
      - description: create new question
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modules.Question'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.RequestResponse'
      summary: create new question
  /question/FetchQuestionsByCourse/{StudentID}/{CourseName}:
    get:
      parameters:
      - description: pass email as StudentID and course name as coursename
        in: path
        name: StudentID
        required: true
        type: string
      - description: courseName as course name
        in: path
        name: CourseName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/question.QuisRequest'
      summary: Fetch question for quis
  /question/TestResult/:
    post:
      parameters:
      - description: Keeps histories of test taken by registered students
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modules.TestResult'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules.RequestResponse'
      summary: Keeps histories of test taken by registered student
  /user/CreateUser:
    post:
      parameters:
      - description: Create new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modules.Student'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules.ResponseManager'
      summary: creates new user
  /user/GetUserFullInfo/{EmailAddress}:
    get:
      parameters:
      - description: user emailAddress
        in: path
        name: EmailAddress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules.Students'
      summary: get user full information
  /user/UpdateUserDetail:
    post:
      parameters:
      - description: Update user information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/modules.Student'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/modules.Message'
      summary: update user details
swagger: "2.0"
